### ISSUE TITLE
Hero / Call to action

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/DHRIFT#20]
Most users will need a big registration link. The design should incorporate a big obvious button for that purpose. It could be something like title, date/time/location lines, then the button, to fit the MUI compoenent default, or whatever.

**Comment by szweibel** [comment]
What would it go to though? I guess customizable to some outside form or etc.

**Comment by smythp** [comment]
They put a link in the config. If there's no link, nothing appears. I don't think we should handle registration, they can use google forms or whatever.

There should probably be a closed / open registration toggle as well?
