### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/DHRIFT#25]
Might be longer term, but SC websites have a section for software install at the bottom that's independent of the specific curriculum.

**Comment by szweibel** [comment]
We do have this in the top menu but they need updating. Could highlight them on the front page too.

**Comment by smythp** [comment]
Good that we have it. Feel like either including on the front page in full or calling out the link to install might be helpful for attendees who are looking for the basics when they go to the event site.
