### ISSUE TITLE
Margin

### ISSUE THREAD

**Issue by smythp** [DHRI-Curriculum/DHRIFT#26]
Consider having some margin on the design, makes things look nicer in many cases.

**Comment by szweibel** [comment]
Do you have any particularly crowded spots in mind?

**Comment by smythp** [comment]
I'm imagining the full page, or possibly the full page after the hero. Something to try when we're more sure about our design. Just think a left-right margin tends to look nice. Let's just try this when we have some other elements and see how it looks, then close this.
