### ISSUE TITLE
Lesson translator/conversion

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#47]

**Comment by szweibel** [comment]
What does this mean?

**Comment by leanne-fan** [comment]
Did we figure out what this meant?

________________________________
From: Stephen Zweibel ***@***.***>
Sent: Friday, March 31, 2023 12:18 PM
To: DHRI-Curriculum/DHRIFT ***@***.***>
Cc: Leanne Fan ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL]Re: [DHRI-Curriculum/DHRIFT] Lesson translator/conversion (Issue #47)

***ATTENTION: This email came from an external source. Do not open attachments or click on links from unknown senders or unexpected emails.***


Closed #47<https://nam12.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FDHRI-Curriculum%2FDHRIFT%2Fissues%2F47&data=05%7C01%7Clfan%40gradcenter.cuny.edu%7C31fbf23e3e9b4544a0c908db32039932%7C0b678335d50a41d3b15230149d930cfa%7C0%7C0%7C638158763266673737%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=fjxHW8uQFyD6NXvMHf2i9i1bZ4auxIsA0pRV4X8YQPA%3D&reserved=0> as completed.

**Comment by szweibel** [comment]
Maybe that we need to move workshops over from the old site.
