### ISSUE TITLE
adding organizer, sponsor, potentially location

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#51]

**Comment by szweibel** [comment]
added date, organization.
<img width="688" alt="image" src="https://user-images.githubusercontent.com/1495183/229573664-f4d6d34d-91bf-4cec-bc2e-f1bd8003d126.png">

**Comment by szweibel** [comment]
Added location 
<img width="624" alt="image" src="https://user-images.githubusercontent.com/1495183/229574152-1a5f8f92-8c71-42fb-a2c9-b9ca24b97ef8.png">
