### ISSUE TITLE
box weirdness

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#54]
<img width="190" alt="Screenshot 2023-03-30 at 11 57 18 AM" src="https://user-images.githubusercontent.com/72720121/228936924-17d519f6-e308-4925-8129-8b84fb6d55f1.png">
^what's going on with the bottom right corner?

also stacking weird, responsiveness to different sizes

**Comment by lmrhody** [comment]
Boxes on drop down workshop menu responsiveness not behaving. Showing crammed in lower right hand corner.

**Comment by szweibel** [comment]
Changed behavior of dropdown
