### ISSUE TITLE
make metadata more robust (description)

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#62]
we want to give users flexibility to add what that way but also maintain some rigidity for magic of yaml!

metadata needs to be more robust, right now in attempt to re-create how it was, the yaml for the workshop is a "bear"

*change "excerpt" to description
*"excerpt" is used a lot in the yaml file incorrectly
*make friendly colors on the highlight!!

We could either get rid of all the magic 
What requires magic

**Comment by szweibel** [comment]
Please split this into separate issues
