### ISSUE TITLE
scroll bar on side confusing

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#65]
either change the color so its different from the rest of the sidebar ToC or add arrows
<img width="160" alt="Screenshot 2023-03-30 at 12 28 21 PM" src="https://user-images.githubusercontent.com/72720121/228943576-f342b237-3fa7-480d-b817-a2fb4f69145a.png">

**Comment by szweibel** [comment]
<img width="83" alt="image" src="https://user-images.githubusercontent.com/1495183/229186411-aad897ce-5f2e-4727-b713-2f77053ebf94.png">
