### ISSUE TITLE
Refining Schedule Feature

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#66]
* "add to your calendar" per day button
* Data under schedule is too big
* "welcome to the dhri" too big (h1?)
* reduce padding between lines within event but increase padding between events
* include "join" button (connect to zoom link) (adding a zoom variable)
* schedule should have links to the workshops
* probably want to link to other things (humanity commons, ("see commons group, see commons profile") or resource materials (providing cheatsheets, articles), link to group library in the commons to download stuff
* any work to be completed in advanced of the workshops (to do items?)

**Comment by szweibel** [comment]
has been divided into multiple issues
