### ISSUE TITLE
CFP for Designer

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#7]

**Comment by smythp** [comment]
I read this over, here are my thoughts:

- This individual will be a contract worker and not salaried, I wouldn't use the word "salary." "Compensation," perhaps?
- The wording makes it sound like they'd be working directly for the NEH. Perhaps something like: "We are seeking a talented and experienced graphic designer to work on a project funded by a grant from the National Endowment for the Humanities (NEH)."
- Branding guidelines? Do we have these? Sounds like comms department boilerplate and is probably not needed.
- Do we care if they have a Bachelor's? I certainly don't. They should have a nice portfolio.
- "Excellent attention to detail and ability to produce high-quality work in a fast-paced environment" Seems somewhat meaningless and impossible to directly acertain.
- Copy a CUNY equal opportunity statement, they're different from others, and this one is oddly worded. For example, Italian Americans are protected as a category at CUNY, for whatever historical reason. 

@szweibel  @leanne-fan

**Comment by leanne-fan** [comment]
Google doc with existing CFP
https://docs.google.com/document/d/1prODX_A5JJ15rBwPhZStUV5opdx-9spxlrljMG_epyI/edit
