### ISSUE TITLE
Update CUNY and Grad Center logos

### ISSUE THREAD

**Issue by leanne-fan** [DHRI-Curriculum/DHRIFT#86]
Current: Outdated logos on all of the websites
Expected: Updated horizontal logos
What done looks like: All the logos are updated?

**Comment by smythp** [comment]
Where are the logos?

**Comment by leanne-fan** [comment]
https://www.gc.cuny.edu/communications-and-marketing/resources-and-services/brand-guide
under LOGOTYPE / WORDMARK
